config/routes.rb
Rails.application.routes.draw do
  resources :properties
  root to: "properties#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/neighbour.rb
class Neighbour < ApplicationRecord
	belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
	has_many :neighbours
	accepts_nested_attributes_for :neighbours,
    :allow_destroy => true,
    :reject_if     => :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
    @neighbour = @property.neighbours.build
  end

  # GET /properties/1/edit
  def edit
    @neighbour = @property.neighbours.blank? ? @property.neighbours.build : @property.neighbours
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :address, neighbours_attributes: [:id, :name, :email, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForm</title>
    <%= csrf_meta_tags %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_for @property do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :property_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :property_address %>
  </div>

  <a href="#" id="add_btn">Add neighbour</a>

  <%= form.fields_for :neighbours do |n| %>
    <div class="neighbour">
      <div class="field">
        <%= n.label :name %>
        <%= n.text_field :name %>
      </div>

      <div class="field">
        <%= n.label :email %>
        <%= n.text_field :email %>
      </div>
      <div>
        <%= n.check_box :_destroy%>
      </div>
      <a href="#" class="remove_btn">Remove</a>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  var n=0;
  $("#add_btn").click(function(e){
    e.preventDefault();
    console.log("CLICK ADD BTN")
    a=$(".neighbour:last").clone();
    a.find("input").each(function(){
      console.log($(this));
    
      if ($(this).attr('id') != undefined){
        id = $(this).attr('id').replace(n, n+1);
        $(this).attr('id', id);
      }
      if ($(this).attr('name') != undefined){
        name = $(this).attr('name').replace(n, n+1);
        $(this).attr('name', name);
      }
    })

    $(a).insertAfter($(".neighbour:last"))
    n=n+1;
  })

  $(".remove_btn").click(function(e){
    e.preventDefault();
    $(this).parent().remove();
  })
</script>

<style type="text/css">
  
  .neighbour{
    margin: 5px;
    border: 1px solid;
  }
</style>

app/views/properties/edit.html.erb
<h1>Editing </h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New </h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>